### ISSUE TITLE
Exception not cought and error message not overly helpful.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#143]
When an exception occurs we should catch that and provide a clean error response.  
The error response should always tell you the user which file was being attempted to be copied so that the user knows what needs to be redone.

The exception below is an example of the sort that needs catching: 

ERROR:: (u'Error parsing capabilities document.', XMLSyntaxError(None,))
Traceback (most recent call last):
  File "/usr/bin/vcp", line 11, in <module>
    load_entry_point('vos==3.1.1', 'console_scripts', 'vcp')()
  File "/usr/lib/python2.7/site-packages/vos/commands/vcp.py", line 102, in vcp
    transfer_shortcut=args.quick)
  File "/usr/lib/python2.7/site-packages/vos/vos.py", line 1442, in __init__
    http_debug=http_debug)
  File "/usr/lib/python2.7/site-packages/vos/vos.py", line 270, in __init__
    session_headers=session_headers)
  File "/usr/lib/python2.7/site-packages/cadcutils/net/ws.py", line 263, in __init__
    base_url = self.caps.get_access_url(SERVICE_AVAILABILITY_ID)
  File "/usr/lib/python2.7/site-packages/cadcutils/net/ws.py", line 635, in get_access_url
    caps.encode('utf-8'))
  File "/usr/lib/python2.7/site-packages/cadcutils/net/wscapabilities.py", line 245, in parsexml
    raise ValueError('Error parsing capabilities document.', e)
ValueError: (u'Error parsing capabilities document.', XMLSyntaxError(None,))

**Comment by ijiraq** [comment]
@andamian if I fix this bug will you do a code review?

**Comment by andamian** [comment]
For sure!
