### ISSUE TITLE
cantop crashes

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#16]
Dear helpdesk,

cantop (part of cadcVOFS) will crash if the terminal is resized, with the following error:

ERROR:astropy:error: addstr() returned ERR
ERROR: error: addstr() returned ERR [vos.cantop]
Traceback (most recent call last):
 File "/Users/michele/Library/Enthought/Canopy_64bit/User/bin/cantop", line 15, in <module>
   cantop.redraw()
 File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/vos/cantop.py", line 90, in redraw
   self.main_window.addstr(self.get_status())
_curses.error: addstr() returned ERR

Cheers

**Comment by ijiraq** [comment]
Cantop is not a supported application.  closing issue.
