### ISSUE TITLE
content length errors in cache.

### ISSUE THREAD

**Issue by ijiraq** [opencadc/vostools#52]
Sometimes there appears to be a dis-connect between the content written to disk and the content expected.  This maybe due to a race condition.

2015-01-05 12:55:48,848 139654004348672 vos-1.11.2fuse._wrapper.411 'NoneType' object has no attribute 'getRange' Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/fuse.py", line 407, in _wrapper
    return func(_args, *_kwargs) or 0
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/fuse.py", line 484, in read
    data = self.operations('read', path.decode(self.encoding), size, offset, fh)
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/vofs.py", line 254, in __call__
    return super(VOFS, self).**call**(op, path, *args)
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/fuse.py", line 848, in **call**
    ret = getattr(self, op)(path, *args)
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/vofs.py", line 569, in read
    return fh.cacheFileHandle.read(size, offset)
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/CadcCache.py", line 1030, in read
    self.makeCached(offset, size)
  File "/usr/lib/python2.6/site-packages/vos-1.11.2-py2.6.egg/vos/CadcCache.py", line 1065, in makeCached
    requiredRange = self.metaData.getRange(firstBlock, lastBlock)
AttributeError: 'NoneType' object has no attribute 'getRange'

**Comment by ijiraq** [comment]
This issue was resolved.
